version = 0.1
[default.deploy.parameters]
stack_name = "AmazonQEvaluationLambda"
resolve_s3 = false
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []